### ISSUE TITLE
posix_memalign not supported

### ISSUE THREAD

**Issue by ramygad** [jbreitbart/malloc_bt#4]
Dear Jens,

I hope you are fine and everything is ok.

I have tested your library against a simple ping pong application, unfortunately I got errors.

I think the problem that when you overload malloc you depend on storing the the size before the allocated memory, when you do free you restore the original allocated memory address and issue the free. (until now there is no problem)

The problem is that not every "free" is done for a "malloc".

A free can be done to "posix_memalign()"

**Comment by jbreitbart** [comment]
Yes that could be the reason for your issues. We only support malloc/free/new/delete at the moment.

The lib was just a quick and dirty experiment to play around with. Pull requests are welcome, but since there are malloc implementations that already support zeroing memory at least as an debug option (e.g. jemalloc IIRC) you are probably better of using these if you look for a feature complete implementation.

**Comment by ramygad** [comment]
Thank you for your reply.

I will try to test "jemalloc IIRC"

Best regards,

Ramy gad
